# Site settings
title: /home/pierce
email: me@dylanjpierce.com
description: > # this means to ignore newlines until "baseurl:"
  Straight forward tutorials for tech minded people.
baseurl: # the subpath of your site, e.g. /blog/
url: "http://blog.dylanjpierce.com" # the base hostname & protocol for your site
twitter_username: ctrlaltdylan
github_username:  ctrlaltdylan

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"



plugins:
  - jekyll-sitemap


markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
